# Generated by Django 3.2.3 on 2021-05-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210520_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='position',
            field=models.CharField(max_length=3),
        ),
    ]
