# Generated by Django 3.2.3 on 2021-05-31 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_gameplayer_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='_teams',
            field=models.ManyToManyField(related_name='games', through='api.GameTeam', to='api.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games', through='api.GamePlayer', to='api.Player'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.game'),
        ),
    ]
